services:
  scra-atlas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scra-atlas
    ports:
      - "5778:5778"
    restart: unless-stopped
    networks:
      - database-common-network

networks:
  database-common-network:
    external: true
    name: database-common-network
